### ISSUE TITLE
GoMobile VC-Wallet Library

### ISSUE THREAD

**Issue by DRK3** [trustbloc/wallet-sdk#1]
- [x] trustbloc/wallet-sdk#3
- [x] trustbloc/wallet-sdk#4
- [x] trustbloc/wallet-sdk#17
- [x] trustbloc/wallet-sdk#18
- [x] trustbloc/wallet-sdk#5 
- [x] trustbloc/wallet-sdk#6
- [x] trustbloc/wallet-sdk#7

(More tasks to be added soon)
