### ISSUE TITLE
GoMobile Reference App 

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/wallet-sdk#2]
- [x] trustbloc/wallet-sdk#8 
- [x] trustbloc/wallet-sdk#9
- [x] trustbloc/wallet-sdk#10
- [x] trustbloc/wallet-sdk#11
- [x] trustbloc/wallet-sdk#12
- [x] trustbloc/wallet-sdk#13
- [x] trustbloc/wallet-sdk#14
